name: Build and Release

on:
  push:
    branches:
      - main # Or specify the branch you want to trigger the workflow on

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.5 # Replace with the Go version you are using

      - name: Build for Linux
        run: go build -o clenc .

      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build -o clenc.exe .

  # release:
  #   name: Create Release
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
      # - name: Checkout repository
      #   uses: actions/checkout@v2

      - name: Extract Version
        id: extract_version
        run: |
          version=$(jq -r '.version' version.json)
          echo "VERSION=${version}" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.VERSION }}
          release_name: Release v${{ env.VERSION }}
          body: |
            Release notes or description of the release.
          draft: false
          prerelease: false

      - name: Upload Executable (Linux)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./clenc
          asset_name: clenc
          asset_content_type: application/octet-stream

      - name: Upload Executable (Windows)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./clenc.exe
          asset_name: clenc.exe
          asset_content_type: application/octet-stream
